### ISSUE TITLE
Wiki syntax error in practice/homework

### ISSUE THREAD

**Issue by thorsteingrimsson** [chriszacny/f5capy002#1]
The problem is with these lines:
print('Value of calculate for n=4 is: ' % calculate(4))
print('Value of calculate for n=12 is: ' % calculate(12))

It returns the following error: TypeError: not all arguments converted during string formatting

They are missing the "%s" for the string formatter to fill in.

**Comment by chriszacny** [comment]
Thanks Thor, fixed.
